trigger: none

pool:
  name: maneesh3456

steps:
- task: TerraformInstaller@1
  displayName: "Terraform Install"
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'
    backendServiceArm: 'maneeshNew connection sep25'
    backendAzureRmResourceGroupName: 'rg_maneesh123'
    backendAzureRmStorageAccountName: 'stgmaneesh22222'
    backendAzureRmContainerName: 'maneeshcontainer123'
    backendAzureRmKey: 'prod.tfstate'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'
    environmentServiceNameAzureRM: 'maneeshNew connection sep25'


- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'
    environmentServiceNameAzureRM: 'maneeshNew connection sep25'

